"""add cwe and ai enrichment fields to vulnerabilities

Revision ID: 0819bf98d6a3
Revises: 
Create Date: 2026-10-06 16:56:14.774030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0819bf98d6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cwe_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cwe_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('owasp_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wstg_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_impact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_remediation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_references', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_generated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vulnerabilities_cwe_id'), ['cwe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_cwe_id'))
        batch_op.drop_column('ai_generated_at')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_provider')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_references')
        batch_op.drop_column('ai_remediation')
        batch_op.drop_column('ai_impact')
        batch_op.drop_column('ai_explanation')
        batch_op.drop_column('wstg_category')
        batch_op.drop_column('owasp_category')
        batch_op.drop_column('cwe_name')
        batch_op.drop_column('cwe_id')

    # ### end Alembic commands ###
